CREATE TABLE IF NOT EXISTS colleges_directory (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  aishe_code VARCHAR(64) NULL,
  college_name VARCHAR(255) NOT NULL,
  university_name VARCHAR(255) NULL,
  college_type VARCHAR(120) NULL,
  management_type VARCHAR(120) NULL,
  course_category VARCHAR(120) NULL,
  city VARCHAR(120) NULL,
  district VARCHAR(120) NULL,
  state VARCHAR(120) NULL,
  pincode VARCHAR(20) NULL,
  address TEXT NULL,
  website_url VARCHAR(255) NULL,
  phone VARCHAR(80) NULL,
  email VARCHAR(180) NULL,
  latitude DECIMAL(10, 7) NULL,
  longitude DECIMAL(10, 7) NULL,
  rating DECIMAL(3, 1) NULL,
  nirf_rank INT NULL,
  source VARCHAR(120) NOT NULL DEFAULT 'AISHE',
  source_url VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_colleges_directory_aishe_code (aishe_code),
  KEY idx_colleges_directory_name (college_name),
  KEY idx_colleges_directory_city (city),
  KEY idx_colleges_directory_district (district),
  KEY idx_colleges_directory_state (state),
  KEY idx_colleges_directory_location (latitude, longitude)
);
